// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../apps/smjs/tpl/element.soy.js', ['sm.template'], ['pstj.material.template', 'pstj.templates', 'soy', 'soydata'], false);
goog.addDependency('../../../apps/smjs/tpl/smjs.soy.js', ['smstb.template'], ['goog.asserts', 'soy', 'soydata'], false);
