// This file was autogenerated by ../../library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../apps/smjs/tpl/smjs.soy.js', ['smstb.template'], ['goog.asserts', 'soy', 'soydata']);
